services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-my-app-server}"
    image: cybulde-data
    platform: linux/amd64
    container_name: cybulde-data-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile  # or just "Dockerfile" if it's in root
      args:
        USER_NAME: "${USER_NAME:-ahmed}"
        USER_ID: "${USER_ID:-1000}"
        HOME: "/home/${USER_NAME:-ahmed}"  # Add this missing argument
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-ahmed}/.config/gcloud
      - ~/ssh:/home/${USER_NAME:-ahmed}/.ssh
      - ./.git:/app/.git
      - ./data/raw:/data/raw
    ports:
      - 8888:8888
    ipc: host
    init: true